base_url = "https://1871.studio"
title = "1871.studio"
description = "1871.studio est un atelier individuel de conception numérique basé à Bordeaux qui vise à concevoir et à fabriquer des produits Web durables et éthiques." 
default_language = "fr"

compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    {name = "tags"},
    {name = "sujets"}
]

[markdown]
highlight_code = true
highlight_theme = "dracula"
external_links_target_blank = true
smart_punctuation = true

[extra]
# Put all your custom variables here